name: flutter_project_template
description: Flutter Template Project

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  # [All]
  # 기본 플러터 개발 도구
  flutter:
    sdk: flutter

  # apple 디자인 아이콘
  cupertino_icons: ^1.0.5

  # Semaphore 사용
  sync: ^0.3.0

  # 스크린 포커스 감지
  focus_detector_v2: ^3.1.0+1

  # Web Url 개선
  url_strategy: ^0.2.0

  # Router 개선
  go_router: ^12.1.3

  # Web SEO 개선
  seo_renderer: ^0.6.0

  # 앱 정보 가져오기
  package_info_plus: ^5.0.1

  # 디바이스 정보 가져오기
  device_info_plus: ^9.1.1

  # SharedPreferences
  shared_preferences: ^2.2.2

  # 네트워크 리퀘스트
  http: ^1.1.2

  # 네트워크 리퀘스트 개선
  dio: ^5.4.0

  # 웹 브라우저 열기
  url_launcher: ^6.2.2

  # Toast
  flutter_styled_toast: ^2.1.3

  # 파일 선택
  # pickFiles (all), getDirectoryPath (web 제외), saveFile (PC), clearTemporaryFiles (Mobile)
  file_picker: ^6.1.1

  # 이미지 파일 선택
  image_picker: ^1.0.5

  # DateTime
  intl: ^0.18.1

  # Gif 재생
  gif: ^2.3.0

  # Dio Logger
  pretty_dio_logger: ^1.3.1

  # 암호화
  encrypt: ^5.0.1

  # JWT 생성
  dart_jsonwebtoken: ^2.12.1

  # HTTP Parser
  http_parser: ^4.0.2

  # image
  image: ^4.1.3

  # Vector Math
  vector_math: ^2.1.4

  ####
  # [Mobile]
  # 앱 스토어 이동
  store_redirect: ^2.0.1

  # 모바일 권한 처리
  permission_handler: ^11.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true

  # 리소스 파일 설정
  assets:
    # 이미지 파일
    - lib/assets/images/

  # 폰트 리소스 설정
  # weight :
  # 100 : thin, 200 : extraLight, 300 : light, 400 : regular, 500 : medium, 600 : semiBold, 700 : bold, 800 : extraBold, 900 : heavy
  fonts:
    - family: MaruBuri
      fonts:
        - asset: lib/assets/fonts/maru_buri/MaruBuri-ExtraLight.otf
          weight: 200
        - asset: lib/assets/fonts/maru_buri/MaruBuri-ExtraLight.ttf
          weight: 200
        - asset: lib/assets/fonts/maru_buri/MaruBuri-Light.otf
          weight: 300
        - asset: lib/assets/fonts/maru_buri/MaruBuri-Light.ttf
          weight: 300
        - asset: lib/assets/fonts/maru_buri/MaruBuri-Regular.otf
          weight: 400
        - asset: lib/assets/fonts/maru_buri/MaruBuri-Regular.ttf
          weight: 400
        - asset: lib/assets/fonts/maru_buri/MaruBuri-SemiBold.otf
          weight: 600
        - asset: lib/assets/fonts/maru_buri/MaruBuri-SemiBold.ttf
          weight: 600
        - asset: lib/assets/fonts/maru_buri/MaruBuri-Bold.otf
          weight: 700
        - asset: lib/assets/fonts/maru_buri/MaruBuri-Bold.ttf
          weight: 700

    - family: SeoulHangang
      fonts:
        - asset: lib/assets/fonts/seoul_hangang/SeoulHangangL.ttf
          weight: 300
        - asset: lib/assets/fonts/seoul_hangang/SeoulHangangM.ttf
          weight: 500
        - asset: lib/assets/fonts/seoul_hangang/SeoulHangangB.ttf
          weight: 700
        - asset: lib/assets/fonts/seoul_hangang/SeoulHangangEB.ttf
          weight: 800

    - family: SeoulHangangZang
      fonts:
        - asset: lib/assets/fonts/seoul_hangang_zang/SeoulHangangZangL.ttf
          weight: 300
        - asset: lib/assets/fonts/seoul_hangang_zang/SeoulHangangZangM.ttf
          weight: 500
        - asset: lib/assets/fonts/seoul_hangang_zang/SeoulHangangZangB.ttf
          weight: 700
        - asset: lib/assets/fonts/seoul_hangang_zang/SeoulHangangZangEB.ttf
          weight: 800
        - asset: lib/assets/fonts/seoul_hangang_zang/SeoulHangangZangBL.ttf
          weight: 900

    - family: SeoulNamsan
      fonts:
        - asset: lib/assets/fonts/seoul_namsan/SeoulNamsanL.ttf
          weight: 300
        - asset: lib/assets/fonts/seoul_namsan/SeoulNamsanM.ttf
          weight: 500
        - asset: lib/assets/fonts/seoul_namsan/SeoulNamsanB.ttf
          weight: 700
        - asset: lib/assets/fonts/seoul_namsan/SeoulNamsanEB.ttf
          weight: 800

    - family: SeoulNamsanZang
      fonts:
        - asset: lib/assets/fonts/seoul_namsan_zang/SeoulNamsanZangL.ttf
          weight: 300
        - asset: lib/assets/fonts/seoul_namsan_zang/SeoulNamsanZangM.ttf
          weight: 500
        - asset: lib/assets/fonts/seoul_namsan_zang/SeoulNamsanZangB.ttf
          weight: 700
        - asset: lib/assets/fonts/seoul_namsan_zang/SeoulNamsanZangEB.ttf
          weight: 800
        - asset: lib/assets/fonts/seoul_namsan_zang/SeoulNamsanZangBL.ttf
          weight: 900